### ISSUE TITLE
Create CI/CD pipeline to add testing

### ISSUE THREAD

**Issue by kenkaijie** [kenkaijie/pyetta#10]
Add github actions for the following:
- [ ] Workflow to package and publish to pypi (on release)
- [ ] Workflow to package, test, and publish to test.pypi (on pre-release/draft)
- [ ] Workflow to test on merge to master

**Comment by SamirPS** [comment]
@kenkaijie can I take this issue  ? When you say test runner is the tests in the folder test ?

**Comment by kenkaijie** [comment]
@SamirPS Sure! I haven't really defined the issue too in detail at the moment, but this was just to extend the existing workflow to run tests, as well as creating another workflow that triggers on pull requests.

**Comment by SamirPS** [comment]
You want to add the test on python-publish ?

**Comment by kenkaijie** [comment]
I've updated the ticket, hopefully that should be sufficient for now. Do you have any suggestions for setting up the workflow?

**Comment by SamirPS** [comment]
For me it's good

**Comment by SamirPS** [comment]
Do you have a requirement.txt file ?

**Comment by kenkaijie** [comment]
There's an initial one in `docs/requirements.txt`. Im planning on moving it out to the root directory soon.

**Comment by SamirPS** [comment]
Okay yeah it's better to move it to the root

**Comment by kenkaijie** [comment]
BTW how did you find out about this project? Might help me when it is closer to a 1.0.0 release (and out of planning status).

**Comment by SamirPS** [comment]
I searched a issue via the issue page on GitHub and i saw your project that all. Do you have a way to contact you more easy that GitHub ?

**Comment by kenkaijie** [comment]
> I searched a issue via the issue page on GitHub and i saw your project that all. Do you have a way to contact you more easy that GitHub ?

I've added #15 for a discord server, that might be the place to discuss various items for now.

**Comment by kenkaijie** [comment]
I am closing this for now, I've placed a skeleton version as a separate test action for now
